version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.13.3-management
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: 'admin'  # Nome de usuário padrão
      RABBITMQ_DEFAULT_PASS: 'admin'  # Senha padrão
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - helpdesk
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  service-discovery:
    image: joanersoncosta/service-discovery
    container_name: 'service-discovery'
    environment:
      - PORT=8761
    ports:
      - "8761:8761"
    expose:
      - 8761
    networks:
      - helpdesk

  config-server:
    image: joanersoncosta/config-server
    container_name: 'config-server'
    environment:
      - CONFIG_SERVER_URI=https://github.com/joanersoncosta/helph-desk-server-configs
      - CONFIG_SERVER_USERNAME=
      - CONFIG_SERVER_PASSWORD=
      - PORT=8888
    ports:
      - "8888:8888"
    expose:
      - 8888
    networks:
      - helpdesk

networks:
    helpdesk:
      driver: bridge