spring:
  application:
    name: api-usuario
  profiles:
    active: ${PROFILE_ACTIVE:dev}   
  config:
    import: "configserver:http://localhost:8888"    
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}  # URL do Config Server
      profile: dev
      label: main