spring:
  application:
    name: api-usuario
  profiles:
    active: ${PROFILE_ACTIVE:dev}   
  config:
    import: "configserver:http://localhost:8888"    
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}  # URL do Config Server
      profile: dev
      label: main
      import-check:
        enabled: false     
         
eureka:  
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}
       
logging:
  level:
    org:
      springframework:
        cloud: DEBUG
    com:
      netflix:
        discovery: DEBUG
        eureka: DEBUG       