spring:
 application:
  name: api-usuario
  
 data:
  mongodb:
   authentication-database: admin
   uri: ${MONGO_DB_URI:mongodb+srv://helpDesk:help-desk-user@wakandadev.cjsar7m.mongodb.net/helpdeskdb?retryWrites=true&w=majority}
   auto-index-creation: true  