spring:
  application:
   name: api-ordem
  profiles:
    active: ${PROFILE_ACTIVE:dev}
  jpa:      
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
      
      