spring:
  application:
    name: 'helpdesk-bff'
  config:
    import: 'configserver:http://localhost:8888'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka/}